version: '3.7'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    networks: 
      - sms

  webapp:
    container_name: webapp
    build:
      context: react-grid/
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    links:
      - postgres
    networks: 
      - sms
    stdin_open: true
  

  # APP*****************************************
  application:
    build:
      context: userProfile/
      dockerfile: Dockerfile
    container_name: application
    expose:
      - 8010
    ports:
      - 8010:8010
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks: 
      - sms
networks: 
  sms: